# [Info]
site_name: uivid64 Space # Top left title
site_url: https://github.com/uivid64/uivid64.github.io
site_author: David
site_description: uivid64 space

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # Day Mode
      primary: indigo # Above
      accent: orange # Highlight
      toggle:
        icon: material/weather-night # Icon Style
        name: Night Mode
    - scheme: slate # Night Mode
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Day Mode
  features:
    - navigation.tabs # Use Tab to sort
    - navigation.top # The button to return to the top appears when sliding up
    - navigation.indexes # Tab will have an index.md instead of opening the first article when the Tab is opened
    - navigation.expand # When the Tab is opened, all the directories on the left are expanded
    - search.suggest # When searching for some letters, it is recommended to complete the whole word
    - search.highlight # The searched article keywords are added to the highlight
  language: zh # Some hints will be changed to Chinese
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # Edit button jump link
## [top-right corner]
repo_url: https://github.com/uivid64/uivid64.github.io # Click the jump link in the upper right corner
repo_name: David Blog
## [bottom-left corner]
copyright: Copyright &copy; 2022 David
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/uivid64
      name: GitHub | uivid64

# [Navigation]
nav:
    - Blog:
      - The Code Review Pyramid: Blog/The Code Review Pyramid.md
      - Learn In Public: Blog/Learn In Public.md
      - Artificial Intelligence: Blog/Artificial Intelligence.md
      - How to Write Software With Mathematical Perfection: Blog/How to Write Software With Mathematical Perfection.md
      - Tips about writing systems papers: Blog/Tips about writing systems papers.md
      - Writing a good paper: Blog/Writing a good paper.md
      - Oral Presentation Advice: Blog/Oral Presentation Advice.md
      - Why numbering should start at zero: Blog/Why numbering should start at zero.md
      - Why does calloc exist: BlogWhy does calloc exist.md
    - Thoughts:
      - Camera on the phone: Thoughts/Camera on the phone.md
      - Personal Preference: Thoughts/Personal Preference.md
      - Pride and Prejudice: Thoughts/Pride and Prejudice.md
      - Love is Wise, Hatred is Foolish: Thoughts/Love is Wise, Hatred is Foolish.md
    - Collection:
      - Campus Capriccio: Collection/campus.md
      - 蜀道難: Collection/shudaonan.md
      - 宋之平蜀: Collection/songzhipingshu.md
    - Develop with Windows 10/11:
      - Python with conda: Windows/conda.md
      - Delete file: Windows/delete_file.md
      - Proxy: Windows/proxy.md
      - Cmd: Windows/cmd.md
      - Win+R: Windows/Win+R.md
      - Windows 11 Tips: Windows/Windows 11.md
      - Winget: Windows/winget.md
      - WSA: Windows/WSA.md
      - WSL: Windows/WSL.md
      - Docker Desktop : Windows/docker.md






# [Extensions]
plugins:
  - search: # Chinese search is not supported yet. After support, you can set the language
    # Insider already supports Chinese word segmentation search https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # Add tags to a single article https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex support
      generic: true
  - attr_list # Add {width="300"} to the back of the picture to set the size
  - toc:
      permalink: true # fix the title position to the current position
  - pymdownx.highlight: # code block highlighting
      linenums: true # show line numbers
      auto_title: true # Display programming language name
  - pymdownx.superfences # code block highlighting plugin
  - meta # supports custom title tags above Markdown files, etc.
extra_javascript:
  #latex support
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax @3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # don't use bottom pager
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
